# Generated by Django 6.0.2 on 2026-02-27 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Категория атауы')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Жаңалықтың тақырыбы')),
                ('description', models.TextField(verbose_name='Жаңалықтың сипаттамасы')),
                ('image_url', models.CharField(max_length=500, verbose_name='Жаңалықтың сурет URL-і')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Жаңалықтың жариялану уақыты')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='qaznews_app.category', verbose_name='Категория')),
            ],
        ),
    ]
