# Generated by Django 6.0.2 on 2026-02-28 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qaznews_app', '0002_advertising'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertising',
            name='name',
            field=models.CharField(default='Жарнама', max_length=255, verbose_name='Жарнаманың атауы'),
        ),
    ]
